### ISSUE TITLE
Error 500 while checking token

### ISSUE THREAD

**Issue by fjcarreterox** [XIMDEX/wp-xowl-client#7]
"NetworkError: 500 Internal Server Error - http://x8.ximdex.net/api/v1/check"

The current response: {"status":"error","message":"You need a valid API key."}

The response when the token is correct: {"status":"ok"}

**Comment by drzippie** [comment]
It's a valid response, the method check tries to validate a token, a not valid token allways returns a 500 (access denied to api)
